{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "919a7a9f-cf8c-403c-888b-5e4f1d1d0031",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "unexpected indent (249401207.py, line 150)",
     "output_type": "error",
     "traceback": [
      "  \u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[21]\u001b[39m\u001b[32m, line 150\u001b[39m\n\u001b[31m    \u001b[39m\u001b[31mst.plotly_chart(fig, use_container_width=True)\u001b[39m\n    ^\n\u001b[31mIndentationError\u001b[39m\u001b[31m:\u001b[39m unexpected indent\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "from datetime import datetime\n",
    "\n",
    "# ---------------- PAGE CONFIG ----------------\n",
    "st.set_page_config(page_title=\"Education Analytics Dashboard\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🎓 Education Analytics Dashboard\")\n",
    "\n",
    "# ---------------- LOAD DATA ----------------\n",
    "# Replace with your actual CSV file names\n",
    "df = pd.read_csv(\"courses.csv\")\n",
    "instructors = pd.read_csv(\"instructors.csv\")\n",
    "\n",
    "# ---------------- SIDEBAR FILTERS ----------------\n",
    "st.sidebar.header(\"🔍 Filters\")\n",
    "\n",
    "level_options = ['All'] + sorted(df['CourseLevel'].unique().tolist())\n",
    "selected_level = st.sidebar.selectbox(\"Select Course Level\", level_options)\n",
    "\n",
    "if selected_level != \"All\":\n",
    "    filtered_df = df[df['CourseLevel'] == selected_level]\n",
    "else:\n",
    "    filtered_df = df.copy()\n",
    "\n",
    "# ---------------- TABS ----------------\n",
    "tab1, tab2, tab3, tab4 = st.tabs([\n",
    "    \"🏆 Top Instructors\",\n",
    "    \"📊 Category Analysis\",\n",
    "    \"📈 Enrollment Trends\",\n",
    "    \"🎯 Expertise Analysis\"\n",
    "])\n",
    "\n",
    "# ======================================================\n",
    "# TAB 1: TOP INSTRUCTORS\n",
    "# ======================================================\n",
    "with tab1:\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "        st.markdown(\"### 🏆 Top 20 Instructors\")\n",
    "\n",
    "        current_instructors = instructors[\n",
    "            instructors['TeacherID'].isin(filtered_df['TeacherID'].unique())\n",
    "        ]\n",
    "\n",
    "        top_instructors = current_instructors.sort_values(\n",
    "            'TeacherRating', ascending=False\n",
    "        ).head(20)\n",
    "\n",
    "        fig = px.bar(\n",
    "            top_instructors,\n",
    "            x='TeacherRating',\n",
    "            y='TeacherName',\n",
    "            orientation='h',\n",
    "            color='TeacherRating',\n",
    "            color_continuous_scale='Blues',\n",
    "            height=600\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.markdown(\"### 📋 Instructor Summary\")\n",
    "        st.dataframe(top_instructors)\n",
    "\n",
    "# ======================================================\n",
    "# TAB 2: CATEGORY ANALYSIS\n",
    "# ======================================================\n",
    "with tab2:\n",
    "    col1, col2 = st.columns(2)\n",
    "\n",
    "    with col1:\n",
    "        st.markdown(\"### 📊 Quality by Category\")\n",
    "\n",
    "        cat_analysis = filtered_df.groupby('CourseCategory').agg({\n",
    "            'CourseRating': 'mean',\n",
    "            'TotalEnrollments': 'sum'\n",
    "        }).reset_index().sort_values('CourseRating', ascending=False)\n",
    "\n",
    "        fig = px.bar(\n",
    "            cat_analysis,\n",
    "            x='CourseRating',\n",
    "            y='CourseCategory',\n",
    "            orientation='h',\n",
    "            color='CourseRating',\n",
    "            color_continuous_scale='Viridis',\n",
    "            height=500\n",
    "        )\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "    with col2:\n",
    "        st.markdown(\"### 📈 Enrollment by Category\")\n",
    "\n",
    "        fig2 = px.pie(\n",
    "            cat_analysis,\n",
    "            names='CourseCategory',\n",
    "            values='TotalEnrollments',\n",
    "            height=500\n",
    "        )\n",
    "        st.plotly_chart(fig2, use_container_width=True)\n",
    "\n",
    "# ======================================================\n",
    "# TAB 3: ENROLLMENT TRENDS\n",
    "# ======================================================\n",
    "with tab3:\n",
    "    st.markdown(\"### 📈 Enrollment Distribution\")\n",
    "\n",
    "    fig = px.histogram(\n",
    "        filtered_df,\n",
    "        x='TotalEnrollments',\n",
    "        nbins=30,\n",
    "        height=500\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ======================================================\n",
    "# TAB 4: EXPERTISE ANALYSIS\n",
    "# ======================================================\n",
    "with tab4:\n",
    "    st.markdown(\"### 🎯 Teacher vs Course Rating\")\n",
    "\n",
    "    expertise_analysis = filtered_df.groupby('Expertise').agg({\n",
    "        'TeacherRating': 'mean',\n",
    "        'CourseRating': 'mean',\n",
    "        'TotalEnrollments': 'sum',\n",
    "        'TeacherID': 'nunique'\n",
    "    }).reset_index()\n",
    "\n",
    "    expertise_analysis.columns = [\n",
    "        'Expertise',\n",
    "        'AvgTeacherRating',\n",
    "        'AvgCourseRating',\n",
    "        'TotalEnrollments',\n",
    "        'NumInstructors'\n",
    "    ]\n",
    "\n",
    "\n",
    "fig = px.scatter(\n",
    "        expertise_analysis,\n",
    "        x='AvgTeacherRating',\n",
    "        y='AvgCourseRating',\n",
    "        size='TotalEnrollments',\n",
    "        color='Expertise',\n",
    "        hover_data=['NumInstructors'],\n",
    "        title=\"Teacher vs Course Rating by Expertise\",\n",
    "        height=500\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# ---------------- FOOTER ----------------\n",
    "st.markdown(\"---\")\n",
    "st.caption(f\"Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "828cc29b-b3b4-409c-8019-b695b94417ae",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2cc046d-8e2c-44fc-b647-d82f9d09a6b0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bc6c49f7-0714-4493-bd27-ac7efba2c6a9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75dc9e45-15c5-41b9-8776-c2dfffdb72fb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
